version: '2'

# ---
#  Startet alle Container, die für den lokalen Betrieb der Lunchbox
#  via "gradle bootRun" notwendig sind.
# ---
services:
  # OpenOCR
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Phaish9ohbaidei6oole"

  strokewidthtransform:
    image: tleyden5iwx/open-ocr-preprocessor
    volumes:
      - ./src/integrationTest/resources/scripts/:/opt/open-ocr/
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-preprocessor -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -preprocessor stroke-width-transform"

  openocrworker:
    image: tleyden5iwx/open-ocr-2
    volumes:
      - ./src/integrationTest/resources/scripts/:/opt/open-ocr/
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
    command: "/opt/open-ocr/open-ocr-worker -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/"

  openocr:
    image: tleyden5iwx/open-ocr-2
    volumes:
      - ./src/integrationTest/resources/scripts/:/opt/open-ocr/
    ports:
      - "9292:9292"
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
      - openocrworker
      - strokewidthtransform
    command: "/opt/open-ocr/open-ocr-httpd -amqp_uri amqp://admin:Phaish9ohbaidei6oole@rabbitmq/ -http_port 9292"
