version: '3'

services:
  frontend-v1:
    image: docker.rori.dev/lunchbox-frontend:1.0
    networks:
      webgateway:
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.lunchbox-frontend-v1.rule: Host(`lunchbox.${BASE_DOMAIN}`)
      traefik.http.routers.lunchbox-frontend-v1.entrypoints: web

  frontend-v2:
    image: docker.rori.dev/lunchbox-frontend:latest
    networks:
      webgateway:
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.lunchbox-frontend-v2.rule: Host(`lunchbox2.${BASE_DOMAIN}`)
      traefik.http.routers.lunchbox-frontend-v2.entrypoints: web

  backend:
    image: docker.rori.dev/lunchbox-backend:latest
    depends_on:
      - openocr
      - rendertron
    networks:
      webgateway:
      default:
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.lunchbox-backend.rule: Host(`lunchbox.${BASE_DOMAIN}`, `lunchbox2.${BASE_DOMAIN}`) && PathPrefix(`/api`, `/feed`)
      traefik.http.routers.lunchbox-backend.entrypoints: web
      traefik.http.services.lunchbox-backend.loadbalancer.server.port: 8080
      # Die Android-App nutzt noch HTTP und kann mit Redirects nicht um
      traefik.http.routers.lunchbox-backend-web80.rule: Host(`lunchbox.${BASE_DOMAIN}`, `lunchbox2.${BASE_DOMAIN}`) && PathPrefix(`/api`, `/feed`)
      traefik.http.routers.lunchbox-backend-web80.entrypoints: web80

  # ---
  #  OpenOCR
  # ---
  rabbitmq:
    image: rabbitmq:3-management-alpine
#    ports:
#      - "5672:5672"
    networks:
      default:
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Phaish9oqbaidex6oole"

  strokewidthtransform:
    image: tleyden5iwx/open-ocr-preprocessor
    volumes:
      - ./scripts/:/opt/open-ocr/
    networks:
      default:
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
    restart: unless-stopped
    command: "/opt/open-ocr/open-ocr-preprocessor -amqp_uri amqp://admin:Phaish9oqbaidex6oole@rabbitmq/ -preprocessor stroke-width-transform"

  openocrworker:
    image: tleyden5iwx/open-ocr-2
    volumes:
      - ./scripts/:/opt/open-ocr/
    networks:
      default:
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
    restart: unless-stopped
    command: "/opt/open-ocr/open-ocr-worker -amqp_uri amqp://admin:Phaish9oqbaidex6oole@rabbitmq/"

  openocr:
    image: tleyden5iwx/open-ocr-2
    volumes:
      - ./scripts/:/opt/open-ocr/
#    ports:
#      - "9292:9292"
    networks:
      default:
    dns: ["8.8.8.8"]
    depends_on:
      - rabbitmq
      - openocrworker
      - strokewidthtransform
    restart: unless-stopped
    command: "/opt/open-ocr/open-ocr-httpd -amqp_uri amqp://admin:Phaish9oqbaidex6oole@rabbitmq/ -http_port 9292"

  # ---
  #  Rendertron
  # ---
  rendertron:
    image: ammobindotca/rendertron
    environment:
      - PORT=3005
    restart: unless-stopped
    networks:
      default:


networks:
  webgateway:
    external: true
